name = "jokeapi"
version = "1.0.3"


description = " gleam library for fetching jokes from the JokeAPI"
licences = ["Apache-2.0"]
repository = { type = "github", user = "johnwesonga", repo = "joker" }


[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_hackney = ">= 1.3.1 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
